<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link rel="shortcut icon" href="images/ors-logo1.png" type="image/x-icon">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Terms & Conditions</title>
  <style>
    /* css goes here  */
    * {
      margin: 0px;
      padding: 0px;
      box-sizing: border-box;
    }

    .terms {
      padding: 24px;
      font-size: 14px;
      text-align: justify;
    }

    .terms h1 {
      font-size: 25px;
      padding: 14px 0px;
    }

    .terms h3 {
      font-size: 18px;
    }
  </style>
</head>

<body>
  <header>
    <?php
    include('header.php');
    ?>
  </header>
  <section class="terms">
    <h1>Terms and Conditions</h1>
    <p>Please read these conditions carefully before using the online recharge site. By using the Online recharge website, you signify your agreement to be bound by these conditions.
      In addition, when you use any current or future Online recharge service ("Online Recharge Service"), you will also be subject to the terms, guidelines and conditions applicable to that Online Recharge Service. ("Terms"). If these Conditions of Use are inconsistent with such Terms, the Terms will control.
      These "Conditions of Use" constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

    <h1>Eligibility</h1>
    <p>register and avail the services of online recharge "User" represents and warrants that he/she has the right, authority, and capacity to enter into this Agreement and to abide by all of the terms of usage of this Agreement. The "User" shall not impersonate any person or entity, or falsely state or otherwise misrepresent identity, age or affiliation with any person or entity.</p>
    <p>Online recharge may terminate the registration of the "User", and any content or information that "User" has posted on online recharge and/or prohibit "User" from using or accessing the Service (or any portion, aspect or feature of the Service) for any reason including the reasons stated above, at any time in its sole discretion, with or without notice, including without limitation. </p>

    <h1>Recharge Plans</h1>
    <h3>Note:</h3>
    <p>- MRP shown on site include service tax & education cess at the current rates.</p>
    <p>- the recharge tariff plans are subject to change by the service provider.</p>
    <p>- tariff plans have been provided for information purposes only. </p>
    <p>- We does not take any responsibility in case these have been changed by the service provider.</p>

    <h1>Conditions Relating to Your Use of Online Recharge </h1>
    <h3>Your Account</h3>
    <p>If you use the website, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer to prevent unauthorised access to your account. You agree to accept responsibility for all activities that occur under your account or password. You should take all necessary steps to ensure that the password is kept confidential and secure and should inform us immediately if you have any reason to believe that your password has become known to anyone else, or if the password is being, or is likely to be, used in an unauthorised manner. Please ensure that the details you provide us with are correct and complete and inform us immediately of any changes to the information that you provided when registering. You can access and update much of the information you provided us with in the Your Account area of the website. You agree and acknowledge that you will use your account on the website to recharge for your personal use and not for business purposes. Online recharge reserves the right to refuse access to the website, terminate accounts.</p>

    <h3>Refund Policy</h3>

    <p>All sales of prepaid recharge on the Online recharge Platform are final with no refund or exchange permitted. You are responsible for the mobile number or DTH account number for which You purchase the prepaid recharge and all charges that result from those purchases. You are also responsible for the information relating to data card and toll-tag recharge and all charges that result from those purchases. Online Recharge site is not responsible for any purchase of prepaid recharge for an incorrect mobile number or DTH account number or incorrect toll or data card information. However, if in a transaction performed by You on the Platform, money has been charged to Your card or bank account and a recharge is not delivered within 24 hours of the completion of the transaction, then You shall inform us by sending an e mail to our customer services e mail address mentioned on the ‘Contact Us’ page on the recharge Platform. Please include in the e-mail the following details – the mobile number (or DTH account number or data card or toll-tag information), operator name, recharge value, transaction date and order number. online recharge site will investigate the incident and, if it is found that money was indeed charged to Your card or bank account without delivery of the recharge, then You will be refunded the money within 21 working days from the date of receipt of Your e mail. All refunds will be credited to Your semi- closed wallet. You can trigger a request in Your wallet to transfer the money from Your wallet back to source. It will take 3-21 working days for the money to show in Your bank account depending on Your bank’s policy.</p>

    <h1>TERMINATION OF SERVICES</h1>
    <h3>Your account may be disabled and Services may be terminated based upon the representations made by you. Any of the following actions may result in termination of Services:</h3>

    <ol>
      <li>Impersonating another person or entity with the effect of misleading users about the identity of the creator of content (including misleading account user names, voices and sounds used in broadcasts, and account profile information);</li>
      <li>Impersonating the Services or a Online Recharge Team member;</li>
      <li>Representing that content you post or transmit through the Services is created or endorsed by us;</li>
      <li>Providing or sending any content which may be harmful or detrimental to Online Recharge or its business associates, or which violates any restriction or policy established by Online Recharge or its business associates;</li>
      <li>Submission of any content that falsely expresses or implies that such content is sponsored or endorsed by us;</li>
      <li>Falsification or deletion of any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is posted;</li>
      <li>Putting on Online Recharge system any content that contains software viruses, trojan horses or any other computer code, files, or programs designed to interrupt, destroy, or limit functionality of any computer software or hardware or telecommunications equipment;</li>
      <li>Manipulating Service identifiers in order to disguise the origin of any content transmitted via the Services;
        Collecting or storing personal data about other users;</li>
      <li>Interfering with or disrupting the Service or servers or networks connected to the Service, or disobeying any requirements, procedures, policies or regulations of networks connected to the Service;</li>
      <li>Using any robot, spider, website search/retrieval application, or other device to retrieve or index any portion of the Service or collect information about users for any unauthorized purpose;</li>
    </ol>
  </section>
  <footer>
    <?php
    include('footer.php');
    ?>
  </footer>
</body>

</html>